# Generated by Django 4.1.2 on 2022-10-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('brazilian_real', models.DecimalField(decimal_places=2, max_digits=9)),
                ('euro', models.DecimalField(decimal_places=2, max_digits=9)),
                ('japanese_yen', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
