# Generated by Django 4.1.2 on 2022-10-27 22:26
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("brazilian_real", models.DecimalField(decimal_places=2, max_digits=9)),
                ("euro", models.DecimalField(decimal_places=2, max_digits=9)),
                ("japanese_yen", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
